Repository ChatAdditions/ChatAdditions_AMXX, pull requests merged in 2020-04, with the labels that each got.

#44 Refactoring?
  amxmodx/scripting/CA_Gag.sma
Labels: enhancement, gag plugin, good first issue

#45 more saferty string into SQL queries
  amxmodx/scripting/include/ChatAdditions_inc/_GameCMS.inc
  amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
  amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
Labels: bug, enhancement, gag plugin, good first issue

#46 fix SQL quotes fmt
  amxmodx/scripting/include/ChatAdditions_inc/_GameCMS.inc
  amxmodx/scripting/include/ChatAdditions_inc/_MySQL.inc
  amxmodx/scripting/include/ChatAdditions_inc/_SQLite.inc
Labels: bug, gag plugin, good first issue
