Repository ChatAdditions/ChatAdditions_AMXX, pull requests merged in 2021-03, with the labels that each got.

#104 Add new command: `amx_gag`
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/include/CA_GAG_API.inc
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Labels: feature

#105 Add support arguments for `say /gag` <nickname> command
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#107 Added notifications to gagged players
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#121 🐛 Reset gag data on player disconnect
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug

#127 Add autoload SQL modules
  cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
Labels: feature

#109 Add support CS:Bans storage provider
  cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
  cstrike/addons/amxmodx/configs/plugins/CA_Storage_CSBans.cfg
  cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
  cstrike/addons/amxmodx/scripting/include/CA_StorageAPI_endpoint.inc
  cstrike/addons/amxmodx/scripting/include/cellqueue.inc
Labels: feature

#114 Add support GameCMS storage provider
  cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
  cstrike/addons/amxmodx/configs/plugins/CA_Storage_GameCMS.cfg
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
Labels: feature

#129 Add support in-game Mute manager
  cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Labels: feature

#131 Add CVar for choose storage type `ca_storage_type`
  cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions.cfg
  cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: feature

#132 Not show `/mute` menu when haven't players
  cstrike/addons/amxmodx/data/lang/CA_Mute.txt
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
Labels: feature

#136 Add gag flags for reasons list
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#143 Add Spanish translation for plugins
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/data/lang/CA_Mute.txt
Labels: feature

#141 New cvars and hide pagination
  cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#144 Add plugin: block dead player voice by timer
  cstrike/addons/amxmodx/configs/plugins-ChatAdditions.ini
  cstrike/addons/amxmodx/configs/plugins/CA_Addon_DeathMute.cfg
  cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Labels: feature

#150 FIX: Error with uninitialized SQL handler
  cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
Labels: bug

#147 Add new CVar: ca_gag_block_nicnkame_change
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Labels: feature

#138 Add artifacts for CI builds
  .github/workflows/build.yml
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
  publish.sh
Labels: feature

#153 FIX: Error when hasn't reasons template
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug

#155 FIX: Wrong gag type by convert
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
Labels: bug

#160 FIX: Dead players can't talk to anyone
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
Labels: bug

#157 added check for 'amx_gag' command, if player already has gag
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: gag plugin

#162 New CVar `ca_deathmute_dead_hear_alive`
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
Labels: feature

#164 Add Lang: [de]
  cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/data/lang/CA_Mute.txt
Labels: feature

#166 Implement CA_Gag API
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/include/CA_GAG_API.inc
Labels: feature

#168 Disabling cmdaccess support for registered plugin commands
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: bug

#169 Add support colors for prefixes
  cstrike/addons/amxmodx/configs/plugins/CA_Addon_DeathMute.cfg
  cstrike/addons/amxmodx/configs/plugins/CA_Gag.cfg
  cstrike/addons/amxmodx/configs/plugins/CA_Mute.cfg
  cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/data/lang/CA_Mute.txt
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
Labels: feature

#170 New path configs (`configs/plugins/*` -> `configs/plugins/ChatAdditions/*`)
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_DeathMute.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Gag.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Mute.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Storage_CSBans.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Storage_GameCMS.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ChatAdditions_core.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ca_gag_reasons.cfg
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: feature

#171 New file-logs names; Folder for each CA plugin
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: feature

#181 Fixed flooding in console
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug

#182 Add new CVar `ca_deathmute_immunity_flags`
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_DeathMute.cfg
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
Labels: feature

#183 CA_Gag: Add block for `amx_tsay`, `amx_csay`
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#189 Small code refactoring & Bug with DeathMute hud fixed
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
Labels: feature

#185 CA_Gag: admin chat block enhancement with new CVar `ca_gag_block_admin_chat`
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Gag.cfg
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#187 CA_Core: Move creating CVar's and reg plugin on precache()
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: bug
