Repository ChatAdditions/ChatAdditions_AMXX, pull requests merged in 2022-09, with the labels that each got.

#278 CA:Gag: fix wrong exit item name
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug

#268 Update `CA_Client_Say()` with new param: `bool: isTeamMessage`
  cstrike/addons/amxmodx/scripting/CA_Addon_RankRestrictions.sma
  cstrike/addons/amxmodx/scripting/CA_Addon_RequestUnGag.sma
  cstrike/addons/amxmodx/scripting/CA_AntiFlood.sma
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
  cstrike/addons/amxmodx/scripting/include/ChatAdditions.inc
Labels: feature

#280 gag: fixed the team chat gag that doesn't work
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug, gag plugin
