Repository ChatAdditions/ChatAdditions_AMXX, pull requests merged in 2022-03, with the labels that each got.

#252 CI: Add release hashes
  .github/workflows/CI.yml
Labels: feature

#257 `EditGag` menu fixes
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: bug

#258 `Mute menu`: Fix `EXIT` item shift
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
Labels: bug

#259 Add `RO` lang
  cstrike/addons/amxmodx/data/lang/CA_Addon_DeathMute.txt
  cstrike/addons/amxmodx/data/lang/CA_Addon_RankRestrictions.txt
  cstrike/addons/amxmodx/data/lang/CA_Addon_RequestUngag.txt
  cstrike/addons/amxmodx/data/lang/CA_AntiFlood.txt
  cstrike/addons/amxmodx/data/lang/CA_Gag.txt
  cstrike/addons/amxmodx/data/lang/CA_Mute.txt
Labels: feature

#261 `RankRestrictions`: Implemented new ranking systems
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_RankRestrictions.cfg
  cstrike/addons/amxmodx/scripting/CA_Addon_RankRestrictions.sma
Labels: feature

#260 Fix admin link in `GameCMS` comms page
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
Labels: bug

#262 `Core`: Implemented `log_to_file_ex` & fixes
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ChatAdditions_core.cfg
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: bug

#266 Add CVar `ca_gag_own_reason_enabled` in CA GAG
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Gag.cfg
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
Labels: feature

#265 Cleanup configs
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_DeathMute.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_RankRestrictions.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Addon_RequestUnGag.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_AntiFlood.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Gag.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Mute.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Storage_CSBans.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Storage_GameCMS.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/CA_Storage_PGBans.cfg
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ChatAdditions_core.cfg
Labels: feature

#264 Update codestyle & minor changes
  cstrike/addons/amxmodx/scripting/CA_Addon_DeathMute.sma
  cstrike/addons/amxmodx/scripting/CA_Addon_RankRestrictions.sma
  cstrike/addons/amxmodx/scripting/CA_Addon_RequestUnGag.sma
  cstrike/addons/amxmodx/scripting/CA_AntiFlood.sma
  cstrike/addons/amxmodx/scripting/CA_Gag.sma
  cstrike/addons/amxmodx/scripting/CA_Mute.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_CSBans.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_PGBans.sma
  cstrike/addons/amxmodx/scripting/CA_Storage_SQLite.sma
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: feature

#263 `Core`: Implement auto delete logs
  cstrike/addons/amxmodx/configs/plugins/ChatAdditions/ChatAdditions_core.cfg
  cstrike/addons/amxmodx/scripting/ChatAdditions_Core.sma
Labels: feature

#272 fix: 🐛 GameCMS: Unsafe name on GetAdminID
  cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
Labels: bug, gag plugin, 💾 Storage
